pipelines:
  default:
    - step:
        name: 'Build docker image'
        script:
        - docker build --platform=linux/amd64 -t "proxy_control_builder" -f ./Dockerfile .
        services:
        - docker