image: saschpe/android-ndk:35-jdk22.0.2_9-ndk27.0.12077973-cmake3.22.1

pipelines:
  default:
    - step:
        name: Build Gradle Project
        caches:
          - gradle
        script:
          - export GRADLE_USER_HOME=`pwd`/.gradle
          - ./gradlew clean build

definitions:
  caches:
    gradle: ~/.gradle
